checks:
  php:
    code_rating: true
    duplication: true
    excluded_dependencies:
      - magento/framework
      - magento/module-catalog-inventory
      - magento/module-cron
      - magento/module-integration
      - magento/module-rss
      - magento/module-theme
      - magento/module-customer
      - magento/module-gift-message
      - magento/module-page-cache
      - magento/module-sales-sequence
      - magento/module-user
      - magento/module-authorization
      - magento/module-developer
      - magento/module-grouped-product
      - magento/module-quote
      - magento/module-security
      - magento/module-wishlist
      - magento/module-catalog-import-export
      - magento/module-directory
      - magento/module-indexer
      - magento/module-require-js
      - magento/module-shipping
      - magento/module-cms
      - magento/module-backend
      - magento/module-catalog
      - magento/module-media-storage
      - magento/module-store
      - magento/module-backup
      - magento/module-cms-url-rewrite
      - magento/module-reports
      - magento/module-translation
      - magento/module-bundle
      - magento/module-downloadable
      - magento/module-sales
      - magento/module-ui
      - magento/module-checkout
      - magento/module-product-alert
      - magento/module-variable
      - magento/module-eav
      - magento/module-contact
      - magento/module-newsletter
      - magento/module-sales-rule
      - magento/module-deploy
      - magento/module-payment
      - magento/module-url-rewrite

filter:
    excluded_paths:
        - "Test/"

build:
    dependencies:
        before:
            - 'echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json'
